-- Create store_settings table
create table if not exists "public"."store_settings" (
    "id" bigint generated by default as identity not null primary key,
    "zelle_id" text default ''::text not null,
    "paypal_id" text default ''::text not null,
    "created_at" timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table "public"."store_settings" enable row level security;

create policy "Enable read access for all users"
on "public"."store_settings"
as permissive
for select
to public
using (true);

-- Add payment columns to orders
alter table "public"."orders" add column if not exists "payment_method" text;
alter table "public"."orders" add column if not exists "payment_id" text;

alter table "public"."orders" drop constraint if exists "orders_payment_method_check";
alter table "public"."orders" add constraint "orders_payment_method_check" check (payment_method = any (array['zelle'::text, 'paypal'::text, 'cash'::text]));

-- Grant access (replicating what is usually default or observed in local dump)
grant all on table "public"."store_settings" to "anon";
grant all on table "public"."store_settings" to "authenticated";
grant all on table "public"."store_settings" to "service_role";
