-- Drop tables that have schema mismatch (UUID vs BIGINT)
drop table if exists "public"."order_items";
drop table if exists "public"."orders";

-- Recreate orders table with BIGINT id matches local
create table "public"."orders" (
    "id" bigint generated by default as identity not null primary key,
    "customer_name" text not null,
    "customer_email" text not null,
    "customer_phone" text not null,
    "total_amount" numeric not null check (total_amount >= 0),
    "status" "public"."order_status" default 'pending'::"public"."order_status" not null,
    "created_at" timestamp with time zone default now(),
    "delivery_method" "public"."delivery_type",
    "delivery_address" text,
    "payment_method" text,
    "payment_id" text,
    constraint "orders_payment_method_check" check (payment_method = any (array['zelle'::text, 'paypal'::text, 'cash'::text]))
);

-- Recreate order_items table
create table "public"."order_items" (
    "item_id" uuid default gen_random_uuid() not null primary key,
    "order_id" bigint not null references "public"."orders"("id") on delete cascade,
    "menu_item_id" uuid not null references "public"."menu_items"("id"),
    "quantity" integer not null check (quantity > 0),
    "price_at_time" numeric not null check (price_at_time >= 0),
    "created_at" timestamp with time zone default now(),
    "order_item_status" "public"."status" default 'pending'::"public"."status"
);

-- Enable RLS
alter table "public"."orders" enable row level security;
alter table "public"."order_items" enable row level security;

-- Add Policies (Permissive for now to match local 'anon' usage)
create policy "Enable all access for all users" on "public"."orders" for all using (true) with check (true);
create policy "Enable all access for all users" on "public"."order_items" for all using (true) with check (true);

-- Enable Realtime
alter publication supabase_realtime add table "public"."orders";
alter publication supabase_realtime add table "public"."order_items";

-- Grants
grant all on table "public"."orders" to "anon";
grant all on table "public"."orders" to "authenticated";
grant all on table "public"."orders" to "service_role";

grant all on table "public"."order_items" to "anon";
grant all on table "public"."order_items" to "authenticated";
grant all on table "public"."order_items" to "service_role";

grant all on sequence "public"."orders_id_seq" to "anon";
grant all on sequence "public"."orders_id_seq" to "authenticated";
grant all on sequence "public"."orders_id_seq" to "service_role";
